# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &CitizenBank
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: CitizenBankMSP

        # ID to load the MSP definition as
        ID: CitizenBankMSP

        MSPDir: ../organizations/peerOrganizations/citizenBank.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CitizenBankMSP.admin', 'CitizenBankMSP.peer', 'CitizenBankMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CitizenBankMSP.admin', 'CitizenBankMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CitizenBankMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CitizenBankMSP.peer')"
